name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet: [ '5.0.x' ]
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, windows-latest, macos-10.15, macos-11.0]
    name: Build and test (${{ matrix.dotnet }} on ${{ matrix.os }})
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build PLists -f netstandard2.1
    - name: Test
      run: dotnet test -f net5.0 --verbosity normal
